### ISSUE TITLE
Issue with APPC Credits

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/appcoins-wallet-android#113]
Hi,
I'm unable to use APPC credits for in-app.
Every time I try I get the popup to buy and when I click on it I get a message "An Error occured, please try again".
I checked on logcal and I'm getting this:
`D/HTTP_TRACE(25610): <---------------------------BEGIN REQUEST---------------------------------->
D/HTTP_TRACE(25610): Request encoded url: POST https://api.blockchainds.com/broker/8.20180518/gateways/appcoins_credits/transactions?wallet.address=0xd505902e4E67f30367E8DA43469952a271453683&wallet.signature=00d0ca05840d7e775b1ad73f5e3c5b8ad86e55191fe252a77ac34451be66ca339d341861d3c0e74122ada351225fa9944add73acaebc780a6fa3592d1df95f2c01
D/HTTP_TRACE(25610): Request decoded url: POST https://api.blockchainds.com/broker/8.20180518/gateways/appcoins_credits/transactions?wallet.address=0xd505902e4E67f30367E8DA43469952a271453683&wallet.signature=00d0ca05840d7e775b1ad73f5e3c5b8ad86e55191fe252a77ac34451be66ca339d341861d3c0e74122ada351225fa9944add73acaebc780a6fa3592d1df95f2c01
D/HTTP_TRACE(25610): =============== Headers ===============
D/HTTP_TRACE(25610):
D/HTTP_TRACE(25610): =============== END Headers ===============
D/HTTP_TRACE(25610): {"price.value":"0.460000000000000019","price.currency":"APPC","wallets.developer":"0x04948cea9e6e31a5b09892b8bf83c4cdb4d1a92c","wallets.oem":"0x0965b2a3e664690315ad20b9e5b0336c19cf172e","origin":"BDS","domain":"it.megasoft78.wordsjungle","product":"it.megasoft78.wordsjungle.small_pack_coins","wallets.store":"0xc41b4160b63d1f9488937f7b66640d2babdbf8ad","type":"INAPP"}
D/HTTP_TRACE(25610): Response timeout: 118ms
D/HTTP_TRACE(25610): Response message:
D/HTTP_TRACE(25610): Response code: 401
D/HTTP_TRACE(25610): Response body:
D/HTTP_TRACE(25610): {"code":"Authorization.Invalid","path":"\/gateways\/*\/transactions","data":null}
D/HTTP_TRACE(25610): =============== Headers ===============
D/HTTP_TRACE(25610): error-path : /gateways/*/transactions
D/HTTP_TRACE(25610): error-code : Authorization.Invalid
D/HTTP_TRACE(25610): server : nginx/1.10.3 (Ubuntu)
D/HTTP_TRACE(25610): content-type : application/json
D/HTTP_TRACE(25610): date : Thu, 08 Nov 2018 05:18:30 GMT
D/HTTP_TRACE(25610):
D/HTTP_TRACE(25610): =============== END Headers ===============
D/HTTP_TRACE(25610):
D/HTTP_TRACE(25610): <-----------------------------END REQUEST--------------------------------->`

Could you help me?

**Comment by Trinkes** [comment]
Can you try again with the new version of the wallet?

**Comment by sanohj** [comment]
Try to update your phone app.

**Comment by megasoft78** [comment]
This is fixed in new AppCoins Wallet version. Thank you. :)

**Comment by Riannon19** [comment]
Hello, I am having an issue similar to this but I have the latest version of the app. I'm having issues with in app purchases and sending appc credits. With sending credits,  it says " something went wrong. try again ". I have reinstalled the app but the issue is still there.

**Comment by Trinkes** [comment]
Hello @Riannon19,
Can you provide me your wallet through email?
fabio.costa@aptoide.com

**Comment by spitfireshelly** [comment]
I have the newest update also and I am having the same problem

**Comment by Reyaz786** [comment]
Hi

**Comment by Reyaz786** [comment]
Give me acreadit
